### ISSUE TITLE
Make form class as default export of index.ts

### ISSUE THREAD

**Issue by Trilmatic** [form-js/forms.js#17]
Set `Form` class as default export.

**Comment by Akash5908** [comment]
@Trilmatic I have a good knowledge in React and I would like to work on it, could you assign this issue to me please?

**Comment by Trilmatic** [comment]
@Akash5908 Hi, sure I have assigned it to you. Thank you for contributing.

**Comment by Trilmatic** [comment]
This issue is concerning the core package and the https://github.com/form-js/forms.js/blob/master/packages/core/src/index.ts index.ts file

**Comment by Akash5908** [comment]
@Trilmatic I changed form class to default.

**Comment by Trilmatic** [comment]
@Akash5908 create a pull request to master please So i can't review the changes. Thank you.

**Comment by Akash5908** [comment]
@Trilmatic I made a pull request can you pls check it?

**Comment by Trilmatic** [comment]
@Akash5908 Merged, thank you for contribution! Could you please star this repo so we reach more people? I think this project might have a potential to grow. Thank you for your time.

**Comment by Akash5908** [comment]
@Trilmatic yeah sure.
