### ISSUE TITLE
Password field improvements

### ISSUE THREAD

**Issue by Trilmatic** [form-js/forms.js#71]
- new option `allowPeek` false by default

when allowPeek option is set to true eye icon appers at input end (https://tabler.io/) among with the possibility to peek/unpeek the password in the input.

The functionality can just change the field `type`  parameter on `inputElement` from `password` to `text` and back.

**Comment by DanielVenable** [comment]
I could work on this. Can you assign this to me?

**Comment by Trilmatic** [comment]
Sure, assigned to you. Thanks!

**Comment by Trilmatic** [comment]
If you want to check how the icons could be implemented, might be best to do through css, same as it is on date fields. The file: packages\core\css\fields\dates.css:61. As icons it can be the `eye` and `eye-off`

**Comment by DanielVenable** [comment]
How do you set up a development server and import it locally?

**Comment by Trilmatic** [comment]
Currently we test the features using [npm link](https://docs.npmjs.com/cli/v9/commands/npm-link) into different local projects but we need a dev server so it is easyer to test features. I have created new issue and will most likely look into that today.

**Comment by Trilmatic** [comment]
> How do you set up a development server and import it locally?

If you pull from master there is now a local server available for local testing.

`npm start` and `npm run watch` are now available more info in More info is in [CONTRIBUTING.md](https://github.com/form-js/forms.js/blob/master/CONTRIBUTING.md). You will still need to build changes in packages.

**Comment by DanielVenable** [comment]
Finished. [https://github.com/form-js/forms.js/pull/79](https://github.com/form-js/forms.js/pull/79)
Let me know if there is anything I need to change.

**Comment by Trilmatic** [comment]
> Finished. #79 Let me know if there is anything I need to change.

Thank you added a few minor comments just regarding the usage of constants, other that that it looks great!

**Comment by Trilmatic** [comment]
Resolved by https://github.com/form-js/forms.js/pull/79
