### ISSUE TITLE
error in the project referenced to the cdn

### ISSUE THREAD

**Issue by Dsgnr-JM** [form-js/forms.js#95]
The library is good but you have an error when you say to load via CDN. If you use the files locally it does not work as it tries to load necessary things and cannot find them

**Comment by Dsgnr-JM** [comment]
excelent

**Comment by Trilmatic** [comment]
@Dsgnr-JM I will be removing the JS deliver from the documentation for now until I figure out the best approach to support both `ES` and `commonjs` through JS Deliver services. Until then please use a package manager for the development. If you have any suggestions or ideas how this could be implemented feel free let me know.
